// import { FormFieldConfig } from './types';

export const FORM_CONFIG: any[] = [
  {
    "checked": true,
    "description": "You can manage your mobile notifications in the mobile settings page.",
    "disabled": false,
    "label": "Use different settings for my mobile devices",
    "name": "name_1954812922",
    "placeholder": "Placeholder",
    "required": true,
    "rowIndex": 0,
    "type": "",
    "value": "",
    "variant": "Checkbox"
  },
  {
    "checked": true,
    "description": "This is the language that will be used in the dashboard.",
    "disabled": false,
    "label": "Language",
    "name": "name_2382739754",
    "placeholder": "Select a language...",
    "required": true,
    "rowIndex": 1,
    "type": "",
    "value": "",
    "variant": "Combobox",
    "options": [
      { "label": "English", "value": "en" },
      { "label": "Spanish", "value": "es" },
      { "label": "French", "value": "fr" },
      { "label": "German", "value": "de" },
      { "label": "Japanese", "value": "ja" }
    ]
  },
  {
    "checked": true,
    "description": "Your date of birth is used to calculate your age.",
    "disabled": false,
    "label": "Date of birth",
    "name": "name_8546526581",
    "placeholder": "Placeholder",
    "required": true,
    "rowIndex": 2,
    "type": "",
    "value": "",
    "variant": "Date Picker"
  },
  {
    "checked": true,
    "description": "Add the date of submission with detailly.",
    "disabled": false,
    "label": "Submission Date",
    "name": "name_2096217527",
    "placeholder": "Placeholder",
    "required": true,
    "rowIndex": 3,
    "type": "",
    "value": "",
    "variant": "Datetime Picker"
  },
  {
    "checked": true,
    "description": "Select a file to upload.",
    "disabled": false,
    "label": "Select File",
    "name": "name_4636054538",
    "placeholder": "Placeholder",
    "required": true,
    "rowIndex": 4,
    "type": "",
    "value": "",
    "variant": "File Input"
  },
  {
    "checked": true,
    "description": "This is your public display name.",
    "disabled": false,
    "label": "Username",
    "name": "name_4814834702",
    "placeholder": "shadcn",
    "required": true,
    "rowIndex": 5,
    "type": "",
    "value": "",
    "variant": "Input"
  },
  {
    "checked": true,
    "description": "Please enter the one-time password sent to your phone.",
    "disabled": false,
    "label": "One-Time Password",
    "name": "name_0756782433",
    "placeholder": "Placeholder",
    "required": true,
    "rowIndex": 6,
    "type": "",
    "value": "",
    "variant": "Input OTP"
  },
  {
    "checked": true,
    "description": "If your country has states, it will be appear after selecting country",
    "disabled": false,
    "label": "Select Country",
    "name": "name_7644590365",
    "placeholder": "Placeholder",
    "required": true,
    "rowIndex": 7,
    "type": "",
    "value": "",
    "variant": "Location Input"
  },
  {
    "checked": true,
    "description": "Select multiple options.",
    "disabled": false,
    "label": "Select your framework",
    "name": "name_3958297779",
    "placeholder": "Placeholder",
    "required": true,
    "rowIndex": 8,
    "type": "",
    "value": "",
    "variant": "Multi Select",
     "options": [
      { "label": "React", "value": "react" },
      { "label": "Vue", "value": "vue" },
      { "label": "Svelte", "value": "svelte" },
      { "label": "Angular", "value": "angular" },
      { "label": "Qwik", "value": "qwik" }
    ]
  },
  {
    "checked": true,
    "description": "Enter your password.",
    "disabled": false,
    "label": "Password",
    "name": "name_0489013225",
    "placeholder": "Placeholder",
    "required": true,
    "rowIndex": 9,
    "type": "",
    "value": "",
    "variant": "Password"
  },
  {
    "checked": true,
    "description": "Enter your phone number.",
    "disabled": false,
    "label": "Phone number",
    "name": "name_9261344596",
    "placeholder": "Placeholder",
    "required": true,
    "rowIndex": 10,
    "type": "",
    "value": "",
    "variant": "Phone"
  },
  {
    "checked": true,
    "description": "Enter your credit card details for payment.",
    "disabled": false,
    "label": "Credit Card Information",
    "name": "name_7034247396",
    "placeholder": "Placeholder",
    "required": true,
    "rowIndex": 11,
    "type": "",
    "value": "",
    "variant": "Credit Card"
  },
  {
    "checked": true,
    "description": "Select your gender",
    "disabled": false,
    "label": "Gender",
    "name": "name_4999468972",
    "placeholder": "Placeholder",
    "required": true,
    "rowIndex": 12,
    "type": "",
    "value": "",
    "variant": "RadioGroup",
    "options": [
        { "label": "Male", "value": "male" },
        { "label": "Female", "value": "female" },
        { "label": "Prefer not to say", "value": "n/a" }
    ]
  },
  {
    "checked": true,
    "description": "Please provide your rating.",
    "disabled": false,
    "label": "Rating",
    "name": "name_5824061107",
    "placeholder": "Placeholder",
    "required": true,
    "rowIndex": 13,
    "type": "",
    "value": "",
    "variant": "Rating"
  },
  {
    "checked": true,
    "description": "You can @mention other users and organizations.",
    "disabled": false,
    "label": "Bio",
    "name": "name_8229695887",
    "placeholder": "Tell us a little bit about yourself",
    "required": true,
    "rowIndex": 14,
    "type": "",
    "value": "",
    "variant": "Textarea"
  },
  {
    "checked": true,
    "description": "Add tags.",
    "disabled": false,
    "label": "Enter your tech stack.",
    "name": "name_3224072544",
    "placeholder": "e.g. React, TypeScript",
    "required": true,
    "rowIndex": 15,
    "type": "",
    "value": "",
    "variant": "Tags Input"
  },
  {
    "checked": true,
    "description": "Receive emails about new products, features, and more.",
    "disabled": false,
    "label": "Marketing emails",
    "name": "name_7234261437",
    "placeholder": "Placeholder",
    "required": true,
    "rowIndex": 16,
    "type": "",
    "value": "",
    "variant": "Switch"
  },
  {
    "checked": true,
    "description": "Please select the full time",
    "disabled": false,
    "label": "What's the best time for you?",
    "name": "name_7687120058",
    "placeholder": "Placeholder",
    "required": true,
    "rowIndex": 17,
    "type": "",
    "value": "",
    "variant": "Smart Datetime Input"
  },
  {
    "checked": true,
    "description": "Adjust the price by sliding.",
    "disabled": false,
    "label": "Set Price Range",
    "name": "name_8928725963",
    "placeholder": "Placeholder",
    "required": true,
    "rowIndex": 18,
    "type": "",
    "value": "",
    "variant": "Slider"
  },
  {
    "checked": true,
    "description": "Please provide your signature above",
    "disabled": false,
    "label": "Sign here",
    "name": "name_8637156202",
    "placeholder": "Placeholder",
    "required": true,
    "rowIndex": 19,
    "type": "",
    "value": "",
    "variant": "Signature Input"
  },
  {
    "checked": true,
    "description": "You can manage email addresses in your email settings.",
    "disabled": false,
    "label": "Email",
    "name": "name_5838842588",
    "placeholder": "Select a verified email to display",
    "required": true,
    "rowIndex": 20,
    "type": "",
    "value": "",
    "variant": "Select",
    "options": [
      { "label": "personal@example.com", "value": "personal" },
      { "label": "work@example.com", "value": "work" }
    ]
  },
  {
    "checked": true,
    "description": "Enter your city.",
    "disabled": false,
    "label": "City",
    "name": "name_1111111111",
    "placeholder": "e.g. San Francisco",
    "required": true,
    "rowIndex": 21,
    "type": "",
    "value": "",
    "variant": "Input"
  },
  {
    "checked": true,
    "description": "Enter your postal code.",
    "disabled": false,
    "label": "Postal Code",
    "name": "name_2222222222",
    "placeholder": "e.g. 94107",
    "required": false,
    "rowIndex": 22,
    "type": "",
    "value": "",
    "variant": "Input"
  },
    {
    "checked": false,
    "description": "Confirm you agree to the terms and conditions.",
    "disabled": false,
    "label": "Agree to Terms",
    "name": "name_33333333333",
    "placeholder": "",
    "required": true,
    "rowIndex": 23,
    "type": "",
    "value": "",
    "variant": "Checkbox"
  },
    {
    "checked": true,
    "description": "Leave a comment for our team.",
    "disabled": false,
    "label": "Additional Comments",
    "name": "name_4444444444",
    "placeholder": "Your feedback is valuable to us...",
    "required": false,
    "rowIndex": 24,
    "type": "",
    "value": "",
    "variant": "Textarea"
  },
  {
    "checked": false,
    "description": "Select all the technologies you are familiar with.",
    "disabled": false,
    "label": "Known Technologies",
    "name": "name_5555555555",
    "placeholder": "",
    "required": true,
    "rowIndex": 25,
    "type": "",
    "value": "",
    "variant": "CheckboxGroup",
    "direction": "vertical",
    "hasOtherOption": true,
    "options": [
      { "label": "React", "value": "react" },
      { "label": "Vue.js", "value": "vue" },
      { "label": "Angular", "value": "angular", "disabled": true },
      { "label": "Svelte", "value": "svelte" }
    ]
  }
];
